---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nestcloud-kubernetes-example-account
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nestcloud-kubernetes-example-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "delete", "create", "patch", "watch"]
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nestcloud-kubernetes-example-role-binding
subjects:
  - kind: ServiceAccount
    name: nestcloud-kubernetes-example-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: nestcloud-kubernetes-example-role
  apiGroup: rbac.authorization.k8s.io
